//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroSharpGanttChart.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicroSharpGanttChart.Locales.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to go project page?.
        /// </summary>
        internal static string aboutAskGoSource {
            get {
                return ResourceManager.GetString("aboutAskGoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string aboutTitle {
            get {
                return ResourceManager.GetString("aboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Count When Important Process:.
        /// </summary>
        internal static string askCount {
            get {
                return ResourceManager.GetString("askCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and close settings in 1 second.
        /// </summary>
        internal static string chkSaveAndCloseInOneSec {
            get {
                return ResourceManager.GetString("chkSaveAndCloseInOneSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit from App?.
        /// </summary>
        internal static string confirmExit {
            get {
                return ResourceManager.GetString("confirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiting.
        /// </summary>
        internal static string confirmExitTitle {
            get {
                return ResourceManager.GetString("confirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to restart App?.
        /// </summary>
        internal static string confirmRestart {
            get {
                return ResourceManager.GetString("confirmRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting.
        /// </summary>
        internal static string confirmRestartTitle {
            get {
                return ResourceManager.GetString("confirmRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        internal static string defaultTimeBlockName {
            get {
                return ResourceManager.GetString("defaultTimeBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License of: {0}.
        /// </summary>
        internal static string licenseTitle {
            get {
                return ResourceManager.GetString("licenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
       
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace MicroSharpGanttChart.Locales {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   A s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Local_Designer {
            get {
                return ResourceManager.GetString("Local_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password:.
        /// </summary>
        internal static string loginLabelEnterPassword {
            get {
                return ResourceManager.GetString("loginLabelEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login: {0}.
        /// </summary>
        internal static string loginTitle {
            get {
                return ResourceManager.GetString("loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Page.
        /// </summary>
        internal static string mainProjectPage {
            get {
                return ResourceManager.GetString("mainProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Repo.
        /// </summary>
        internal static string mainProjectRepo {
            get {
                return ResourceManager.GetString("mainProjectRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom chart background color:.
        /// </summary>
        internal static string setCustomChartBackColor {
            get {
                return ResourceManager.GetString("setCustomChartBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days in chart:.
        /// </summary>
        internal static string setDaysInChart {
            get {
                return ResourceManager.GetString("setDaysInChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day ending hour:.
        /// </summary>
        internal static string setEndHourInDay {
            get {
                return ResourceManager.GetString("setEndHourInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator bottom triangle.
        /// </summary>
        internal static string setIndicatorBottomTriangle {
            get {
                return ResourceManager.GetString("setIndicatorBottomTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator color:.
        /// </summary>
        internal static string setIndicatorColor {
            get {
                return ResourceManager.GetString("setIndicatorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator top triangle.
        /// </summary>
        internal static string setIndicatorTopTriangle {
            get {
                return ResourceManager.GetString("setIndicatorTopTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show days ago (today = 0) :.
        /// </summary>
        internal static string setShowDaysAgo {
            get {
                return ResourceManager.GetString("setShowDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show now indicator.
        /// </summary>
        internal static string setShowNowIndicator {
            get {
                return ResourceManager.GetString("setShowNowIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day start hour:.
        /// </summary>
        internal static string setStartHourInDay {
            get {
                return ResourceManager.GetString("setStartHourInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string setTabAppearance {
            get {
                return ResourceManager.GetString("setTabAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string setTabGeneral {
            get {
                return ResourceManager.GetString("setTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string settingCancel {
            get {
                return ResourceManager.GetString("settingCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm when exiting app.
        /// </summary>
        internal static string settingConfirmExit {
            get {
                return ResourceManager.GetString("settingConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm when restarting app.
        /// </summary>
        internal static string settingConfirmRestart {
            get {
                return ResourceManager.GetString("settingConfirmRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Defaults.
        /// </summary>
        internal static string settingLoadDefaults {
            get {
                return ResourceManager.GetString("settingLoadDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password when logging in:.
        /// </summary>
        internal static string settingPasswordLogin {
            get {
                return ResourceManager.GetString("settingPasswordLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string settingSaveChanges {
            get {
                return ResourceManager.GetString("settingSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded default values.
        /// </summary>
        internal static string settingsLoadedDefaults {
            get {
                return ResourceManager.GetString("settingsLoadedDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Changes..
        /// </summary>
        internal static string settingsSavedChanges {
            get {
                return ResourceManager.GetString("settingsSavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at Windows Startup.
        /// </summary>
        internal static string settingStartup {
            get {
                return ResourceManager.GetString("settingStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Settings.
        /// </summary>
        internal static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe you changed app location or name.
        ///Re check this box to save changes..
        /// </summary>
        internal static string settingsWarningStartup {
            get {
                return ResourceManager.GetString("settingsWarningStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system color picker.
        /// </summary>
        internal static string setUseSystemColorPicker {
            get {
                return ResourceManager.GetString("setUseSystemColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        internal static string strAddRow {
            get {
                return ResourceManager.GetString("strAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rows.
        /// </summary>
        internal static string strAddRows {
            get {
                return ResourceManager.GetString("strAddRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task: {0}.
        /// </summary>
        internal static string strAddTimeBlock {
            get {
                return ResourceManager.GetString("strAddTimeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string strAddTimeBlockTitle {
            get {
                return ResourceManager.GetString("strAddTimeBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Add Row.
        /// </summary>
        internal static string strConfirmAddRow {
            get {
                return ResourceManager.GetString("strConfirmAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Add Rows.
        /// </summary>
        internal static string strConfirmAddRows {
            get {
                return ResourceManager.GetString("strConfirmAddRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string strConfirmDelete {
            get {
                return ResourceManager.GetString("strConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletes.
        /// </summary>
        internal static string strConfirmDeletes {
            get {
                return ResourceManager.GetString("strConfirmDeletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string strConfirmOpenChart {
            get {
                return ResourceManager.GetString("strConfirmOpenChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Rename.
        /// </summary>
        internal static string strConfirmRename {
            get {
                return ResourceManager.GetString("strConfirmRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        internal static string strDeleteRow {
            get {
                return ResourceManager.GetString("strDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Rows.
        /// </summary>
        internal static string strDeleteRows {
            get {
                return ResourceManager.GetString("strDeleteRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string stripAbout {
            get {
                return ResourceManager.GetString("stripAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string stripEdit {
            get {
                return ResourceManager.GetString("stripEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string stripExit {
            get {
                return ResourceManager.GetString("stripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string stripLicense {
            get {
                return ResourceManager.GetString("stripLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string stripRestart {
            get {
                return ResourceManager.GetString("stripRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string stripSettings {
            get {
                return ResourceManager.GetString("stripSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Chart.
        /// </summary>
        internal static string strOpenChartWithString {
            get {
                return ResourceManager.GetString("strOpenChartWithString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Row.
        /// </summary>
        internal static string strRename {
            get {
                return ResourceManager.GetString("strRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string timeblockCancel {
            get {
                return ResourceManager.GetString("timeblockCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string timeblockColor {
            get {
                return ResourceManager.GetString("timeblockColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Changes.
        /// </summary>
        internal static string timeblockConfirmChanges {
            get {
                return ResourceManager.GetString("timeblockConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time:.
        /// </summary>
        internal static string timeblockEndTime {
            get {
                return ResourceManager.GetString("timeblockEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatched.
        /// </summary>
        internal static string timeblockHatched {
            get {
                return ResourceManager.GetString("timeblockHatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string timeblockNameLabel {
            get {
                return ResourceManager.GetString("timeblockNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        internal static string timeblockStartTime {
            get {
                return ResourceManager.GetString("timeblockStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Settings.
        /// </summary>
        internal static string timeblockTitle {
            get {
                return ResourceManager.GetString("timeblockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string timeblockVisible {
            get {
                return ResourceManager.GetString("timeblockVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Multiple Rows.
        /// </summary>
        internal static string toolAddMultiRows {
            get {
                return ResourceManager.GetString("toolAddMultiRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        internal static string toolAddRow {
            get {
                return ResourceManager.GetString("toolAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Single Row.
        /// </summary>
        internal static string toolAddSingleRow {
            get {
                return ResourceManager.GetString("toolAddSingleRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string toolAdvanced {
            get {
                return ResourceManager.GetString("toolAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Chart to ClipBoard.
        /// </summary>
        internal static string toolAdvancedCopyChart {
            get {
                return ResourceManager.GetString("toolAdvancedCopyChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Chart from ClipBoard.
        /// </summary>
        internal static string toolAdvancedPasteChart {
            get {
                return ResourceManager.GetString("toolAdvancedPasteChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string toolDelete {
            get {
                return ResourceManager.GetString("toolDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Rows.
        /// </summary>
        internal static string toolDeleteAll {
            get {
                return ResourceManager.GetString("toolDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rows Except: {0}.
        /// </summary>
        internal static string toolDeleteExceptThis {
            get {
                return ResourceManager.GetString("toolDeleteExceptThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        internal static string toolDeleteRow {
            get {
                return ResourceManager.GetString("toolDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Rows.
        /// </summary>
        internal static string toolDeleteRows {
            get {
                return ResourceManager.GetString("toolDeleteRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Task: {0}.
        /// </summary>
        internal static string toolDeleteTimeBlock {
            get {
                return ResourceManager.GetString("toolDeleteTimeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task Name: {0}.
        /// </summary>
        internal static string toolEditTimeBlockName {
            get {
                return ResourceManager.GetString("toolEditTimeBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string toolFile {
            get {
                return ResourceManager.GetString("toolFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go FullScreen.
        /// </summary>
        internal static string toolFullScreen {
            get {
                return ResourceManager.GetString("toolFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string toolHelp {
            get {
                return ResourceManager.GetString("toolHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show Task: {0}.
        /// </summary>
        internal static string toolHideTimeBlock {
            get {
                return ResourceManager.GetString("toolHideTimeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string toolNew {
            get {
                return ResourceManager.GetString("toolNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Row.
        /// </summary>
        internal static string toolNewRow {
            get {
                return ResourceManager.GetString("toolNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rows....
        /// </summary>
        internal static string toolNewRows {
            get {
                return ResourceManager.GetString("toolNewRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New TimeBlock.
        /// </summary>
        internal static string toolNewTimeBlock {
            get {
                return ResourceManager.GetString("toolNewTimeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Chart....
        /// </summary>
        internal static string toolOpenChart {
            get {
                return ResourceManager.GetString("toolOpenChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Operations: {0}.
        /// </summary>
        internal static string toolQuickOperations {
            get {
                return ResourceManager.GetString("toolQuickOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string toolSaveChanges {
            get {
                return ResourceManager.GetString("toolSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Row: {0}.
        /// </summary>
        internal static string toolSelectedClearRow {
            get {
                return ResourceManager.GetString("toolSelectedClearRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Icon: {0}.
        /// </summary>
        internal static string toolSelectedDeleteIcon {
            get {
                return ResourceManager.GetString("toolSelectedDeleteIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row: {0}.
        /// </summary>
        internal static string toolSelectedDeleteRow {
            get {
                return ResourceManager.GetString("toolSelectedDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Row Name: {0}.
        /// </summary>
        internal static string toolSelectedEditRow {
            get {
                return ResourceManager.GetString("toolSelectedEditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Row: {0}.
        /// </summary>
        internal static string toolSelectedHideRow {
            get {
                return ResourceManager.GetString("toolSelectedHideRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: {0}.
        /// </summary>
        internal static string toolSelectedRow {
            get {
                return ResourceManager.GetString("toolSelectedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Icon: {0}.
        /// </summary>
        internal static string toolSelectedSetIconRow {
            get {
                return ResourceManager.GetString("toolSelectedSetIconRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Settings.
        /// </summary>
        internal static string toolSettingsTimeBlock {
            get {
                return ResourceManager.GetString("toolSettingsTimeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort All Rows.
        /// </summary>
        internal static string toolSortAllRows {
            get {
                return ResourceManager.GetString("toolSortAllRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort All A-Z.
        /// </summary>
        internal static string toolSortRowsAZ {
            get {
                return ResourceManager.GetString("toolSortRowsAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort All Z-A.
        /// </summary>
        internal static string toolSortRowsZA {
            get {
                return ResourceManager.GetString("toolSortRowsZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperate your rownames with &apos;|&apos; character.
        ///Example: MyLittleRow 1 | SecondRoww | Nameless R O W | MoMeMo RoWWW23.
        /// </summary>
        internal static string tooltipSampleAddMultiRow {
            get {
                return ResourceManager.GetString("tooltipSampleAddMultiRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toRight {
            get {
                object obj = ResourceManager.GetObject("toRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Clear All TimeBlocks In: {0} ?.
        /// </summary>
        internal static string wrnClearRow {
            get {
                return ResourceManager.GetString("wrnClearRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Delete All Rows?.
        /// </summary>
        internal static string wrnDeleteAllRows {
            get {
                return ResourceManager.GetString("wrnDeleteAllRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Rows Except: {0} ?.
        /// </summary>
        internal static string wrnDeleteAllRowsExcept {
            get {
                return ResourceManager.GetString("wrnDeleteAllRowsExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Delete: {0}.
        /// </summary>
        internal static string wrnDeleteRow {
            get {
                return ResourceManager.GetString("wrnDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Delete: {0} ?.
        /// </summary>
        internal static string wrnDeleteTimeBlock {
            get {
                return ResourceManager.GetString("wrnDeleteTimeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Hide: {0} ?.
        /// </summary>
        internal static string wrnHide {
            get {
                return ResourceManager.GetString("wrnHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Hide: {0} ?.
        /// </summary>
        internal static string wrnHideTimeBlock {
            get {
                return ResourceManager.GetString("wrnHideTimeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Problem..
        /// </summary>
        internal static string wrnNoProblem {
            get {
                return ResourceManager.GetString("wrnNoProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing has been changed..
        /// </summary>
        internal static string wrnNothingChanged {
            get {
                return ResourceManager.GetString("wrnNothingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid..
        /// </summary>
        internal static string wrnNotValidString {
            get {
                return ResourceManager.GetString("wrnNotValidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Overwrite?.
        /// </summary>
        internal static string wrnOverwrite {
            get {
                return ResourceManager.GetString("wrnOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot processed. Same named Row already exist. Please Give Another Name..
        /// </summary>
        internal static string wrnSameRowAvailable {
            get {
                return ResourceManager.GetString("wrnSameRowAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot processed: {0}
        ///Same named rows already exist..
        /// </summary>
        internal static string wrnSameRowsAvailable {
            get {
                return ResourceManager.GetString("wrnSameRowsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Save Current Chart?.
        /// </summary>
        internal static string wrnSaveCurrentChart {
            get {
                return ResourceManager.GetString("wrnSaveCurrentChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Sort All Rows?.
        /// </summary>
        internal static string wrnSortAllRows {
            get {
                return ResourceManager.GetString("wrnSortAllRows", resourceCulture);
            }
        }
    }
}
