//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroSharpGanttChart {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PasswordLogin {
            get {
                return ((bool)(this["PasswordLogin"]));
            }
            set {
                this["PasswordLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PasswordLoginStr {
            get {
                return ((string)(this["PasswordLoginStr"]));
            }
            set {
                this["PasswordLoginStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfirmExiting {
            get {
                return ((bool)(this["ConfirmExiting"]));
            }
            set {
                this["ConfirmExiting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfirmRestart {
            get {
                return ((bool)(this["ConfirmRestart"]));
            }
            set {
                this["ConfirmRestart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 230, 250")]
        public global::System.Drawing.Color ChartBG {
            get {
                return ((global::System.Drawing.Color)(this["ChartBG"]));
            }
            set {
                this["ChartBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSystemColorPicker {
            get {
                return ((bool)(this["UseSystemColorPicker"]));
            }
            set {
                this["UseSystemColorPicker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DaysInChart {
            get {
                return ((int)(this["DaysInChart"]));
            }
            set {
                this["DaysInChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShowBackDays {
            get {
                return ((int)(this["ShowBackDays"]));
            }
            set {
                this["ShowBackDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNowIndicator {
            get {
                return ((bool)(this["ShowNowIndicator"]));
            }
            set {
                this["ShowNowIndicator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int EndHourInDay {
            get {
                return ((int)(this["EndHourInDay"]));
            }
            set {
                this["EndHourInDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartHourInDay {
            get {
                return ((int)(this["StartHourInDay"]));
            }
            set {
                this["StartHourInDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveAndCloseSettings {
            get {
                return ((bool)(this["SaveAndCloseSettings"]));
            }
            set {
                this["SaveAndCloseSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool indicatorBottomTriangle {
            get {
                return ((bool)(this["indicatorBottomTriangle"]));
            }
            set {
                this["indicatorBottomTriangle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool indicatorTopTriangle {
            get {
                return ((bool)(this["indicatorTopTriangle"]));
            }
            set {
                this["indicatorTopTriangle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("New TimeBlock")]
        public string defaultTimeBlockText {
            get {
                return ((string)(this["defaultTimeBlockText"]));
            }
            set {
                this["defaultTimeBlockText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool defaultTimeBlockVisible {
            get {
                return ((bool)(this["defaultTimeBlockVisible"]));
            }
            set {
                this["defaultTimeBlockVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool defaultTimeBlockHatched {
            get {
                return ((bool)(this["defaultTimeBlockHatched"]));
            }
            set {
                this["defaultTimeBlockHatched"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190, 130, 120")]
        public global::System.Drawing.Color defaultTimeBlockBackColor {
            get {
                return ((global::System.Drawing.Color)(this["defaultTimeBlockBackColor"]));
            }
            set {
                this["defaultTimeBlockBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int defaultTimeBlockAddHour {
            get {
                return ((int)(this["defaultTimeBlockAddHour"]));
            }
            set {
                this["defaultTimeBlockAddHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int askCountDeleteEverything {
            get {
                return ((int)(this["askCountDeleteEverything"]));
            }
            set {
                this["askCountDeleteEverything"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color indicatorColor {
            get {
                return ((global::System.Drawing.Color)(this["indicatorColor"]));
            }
            set {
                this["indicatorColor"] = value;
            }
        }
    }
}
